# Generated by Django 6.0.6 on 2026-06-21 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='saas_core.workspace'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['workspace', 'is_deleted'], name='lumo_identi_workspa_9ecc1d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('workspace', 'name')},
        ),
    ]
