# Generated by Django 6.0.6 on 2026-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_companies',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_customers',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_storage_mb',
            field=models.IntegerField(default=500),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(default=1),
        ),
    ]
