# Generated by Django 6.0.6 on 2026-06-21 15:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_masterdata', '0001_initial'),
        ('saas_core', '0002_subscriptionplan_max_companies_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planprice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='planprice',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Auto-assign to new workspaces'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='trial_days',
            field=models.IntegerField(default=14, help_text='Number of free trial days'),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='snapshot_billing_cycle',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='snapshot_currency_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='snapshot_plan_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='snapshot_plan_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='snapshot_price_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='workspacesubscription',
            name='snapshot_taken_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plan_prices', to='core_masterdata.currency'),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='saas_core.planprice'),
        ),
        migrations.AddConstraint(
            model_name='planprice',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_archived', False)), fields=('plan', 'currency', 'billing_cycle'), name='uniq_active_price_per_plan_currency_cycle'),
        ),
        migrations.AddConstraint(
            model_name='subscriptionplan',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='only_one_default_plan'),
        ),
    ]
