# Generated by Django 6.0.6 on 2026-06-21 15:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0003_alter_planprice_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'lumo_finance_payment_gateway',
            },
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='status',
            field=models.CharField(choices=[('TRIALING', 'Trialing'), ('PENDING_PAYMENT', 'Pending Payment'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('SUSPENDED', 'Suspended'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired')], default='TRIALING', max_length=20),
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('account_name', models.CharField(help_text='e.g., Lumo OS bKash Merchant', max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('branch_name', models.CharField(blank=True, max_length=100, null=True)),
                ('routing_number', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='saas_core.paymentgateway')),
            ],
            options={
                'db_table': 'lumo_finance_payment_account',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('snapshot_plan_name', models.CharField(max_length=100)),
                ('snapshot_price_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('snapshot_currency_code', models.CharField(max_length=10)),
                ('snapshot_billing_cycle', models.CharField(max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('proration_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Processing Verification'), ('COMPLETED', 'Completed & Provisioned'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.subscriptionplan')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.planprice')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='saas_core.workspace')),
            ],
            options={
                'db_table': 'lumo_finance_subscription_order',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender_account_number', models.CharField(help_text="User's bKash/Bank A/C number", max_length=100)),
                ('transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('proof_file', models.FileField(blank=True, null=True, upload_to='payment_proofs/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Settled'), ('FAILED', 'Failed / Rejected')], default='PENDING', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('admin_note', models.TextField(blank=True, help_text='Reason for rejection or verification note', null=True)),
                ('receiving_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='saas_core.paymentaccount')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_payments', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas_core.workspace')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='saas_core.subscriptionorder')),
            ],
            options={
                'db_table': 'lumo_finance_payment_transaction',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('invoice_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('billed_to_company_name', models.CharField(max_length=255)),
                ('billed_to_email', models.EmailField(max_length=254)),
                ('billed_to_address', models.TextField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open / Unpaid'), ('PAID', 'Paid'), ('VOID', 'Void'), ('UNCOLLECTIBLE', 'Uncollectible')], default='DRAFT', max_length=20)),
                ('public_token', models.CharField(db_index=True, max_length=128, unique=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='saas_core.workspace')),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='saas_core.subscriptionorder')),
            ],
            options={
                'db_table': 'lumo_finance_invoice',
                'ordering': ['-issue_date'],
            },
        ),
    ]
