# Generated by Django 6.0.6 on 2026-06-21 19:11

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_masterdata', '0001_initial'),
        ('saas_core', '0005_invoicelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='billed_to_tax_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='billed_to_tax_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='snapshot_tax_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='snapshot_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PAID', 'Paid')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='admin_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='sender_account_number',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='BillingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('legal_company_name', models.CharField(max_length=255)),
                ('billing_email', models.EmailField(max_length=254)),
                ('address_line', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_registration_type', models.CharField(blank=True, choices=[('TIN', 'Tax Identification Number (TIN)'), ('BIN', 'Business Identification Number (BIN)'), ('VAT', 'VAT Registration Number'), ('GST', 'Goods and Services Tax (GST) Number'), ('EIN', 'Employer Identification Number (EIN)'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('tax_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_tax_exempt', models.BooleanField(default=False)),
                ('tax_exemption_certificate', models.FileField(blank=True, null=True, upload_to='tax_exemptions/%Y/%m/')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core_masterdata.country')),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to='saas_core.workspace')),
            ],
            options={
                'db_table': 'lumo_finance_billing_profile',
            },
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('name', models.CharField(help_text='e.g. BD VAT 15%', max_length=50)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core_masterdata.country')),
            ],
            options={
                'db_table': 'lumo_finance_tax_rate',
            },
        ),
    ]
