# Generated by Django 6.0.6 on 2026-06-22 14:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0006_invoice_billed_to_tax_id_invoice_billed_to_tax_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('site_name', models.CharField(default='Lumo OS', max_length=100)),
                ('support_email', models.EmailField(default='support@lumo-os.com', max_length=254)),
                ('default_timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'db_table': 'lumo_global_config',
            },
        ),
        migrations.CreateModel(
            name='WorkspacePreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('invoice_prefix', models.CharField(default='INV-', help_text='e.g. INV-2026-', max_length=10)),
                ('timezone', models.CharField(default='Asia/Dhaka', max_length=50)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=20)),
                ('theme_color', models.CharField(default='default', max_length=20)),
                ('reply_to_email', models.EmailField(blank=True, help_text='Custom email for sending invoices', max_length=254, null=True)),
                ('workspace', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='saas_core.workspace')),
            ],
            options={
                'db_table': 'lumo_workspace_preference',
            },
        ),
        migrations.CreateModel(
            name='PaymentGatewayConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_test_mode', models.BooleanField(default=True)),
                ('api_key', models.CharField(blank=True, help_text='Public Key / Store ID / Client ID', max_length=255, null=True)),
                ('api_secret', models.CharField(blank=True, help_text='Secret Key / Store Password', max_length=255, null=True)),
                ('webhook_secret', models.CharField(blank=True, help_text='Webhook Signing Secret', max_length=255, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_configs', to='saas_core.paymentgateway')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gateway_credentials', to='saas_core.workspace')),
            ],
            options={
                'db_table': 'lumo_payment_gateway_config',
                'constraints': [models.UniqueConstraint(fields=('workspace', 'gateway'), name='unique_workspace_gateway_config')],
            },
        ),
    ]
