# Generated by Django 6.0.6 on 2026-06-23 13:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0007_globalconfiguration_workspacepreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Payment'), ('PROCESSING', 'Processing Verification'), ('COMPLETED', 'Completed & Provisioned'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired'), ('REFUNDED', 'Refunded'), ('CANCELED', 'Canceled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('event_id', models.CharField(db_index=True, help_text='The unique event ID from Stripe/bKash', max_length=255, unique=True)),
                ('gateway_name', models.CharField(help_text="e.g. 'stripe', 'bkash'", max_length=50)),
                ('event_type', models.CharField(help_text="e.g. 'checkout.session.completed'", max_length=100)),
                ('status', models.CharField(default='PROCESSED', help_text='PROCESSED, FAILED, IGNORED', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lumo_finance_webhook_event',
                'indexes': [models.Index(fields=['event_id', 'gateway_name'], name='lumo_financ_event_i_51ac1f_idx')],
            },
        ),
    ]
