# Generated by Django 6.0.6 on 2026-06-23 16:08

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0008_alter_subscriptionorder_status_processedwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billed_to_address',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billed_to_company_name',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billed_to_email',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billed_to_tax_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='billed_to_tax_type',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='issue_date',
        ),
        migrations.RemoveField(
            model_name='subscriptionorder',
            name='created_by_id',
        ),
        migrations.AddField(
            model_name='invoice',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='secure/invoices/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_base_currency',
            field=models.CharField(default='USD', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_billing_address',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_billing_email',
            field=models.EmailField(default=1, editable=False, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_company_name',
            field=models.CharField(default=1, editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_display_currency',
            field=models.CharField(default=1, editable=False, max_length=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_exchange_rate',
            field=models.DecimalField(decimal_places=6, default=1.0, editable=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_tax_id',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='snapshot_tax_type',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='tax_exemption_certificate',
            field=models.FileField(blank=True, null=True, upload_to='secure/tax_exemptions/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(db_index=True, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='saas_core.subscriptionorder'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='public_token',
            field=models.CharField(db_index=True, editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ISSUED', 'Issued'), ('PAID', 'Paid'), ('PARTIALLY_PAID', 'Partially Paid'), ('VOID', 'Void / Cancelled'), ('REFUNDED', 'Refunded / Credit Note')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='description',
            field=models.CharField(editable=False, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='is_tax',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='invoicelineitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='secure/payment_proofs/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified & Settled'), ('FAILED', 'Failed / Rejected'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded'), ('DISPUTED', 'Disputed'), ('CHARGEBACK', 'Chargeback')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='proration_credit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='snapshot_billing_cycle',
            field=models.CharField(editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='snapshot_currency_code',
            field=models.CharField(editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='snapshot_plan_name',
            field=models.CharField(editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='snapshot_price_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='snapshot_tax_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='snapshot_tax_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=5),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12),
        ),
        migrations.AlterField(
            model_name='subscriptionorder',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=12),
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('credit_note_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('amount_credited', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('reason', models.TextField(help_text='Reason for the refund / credit')),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='secure/credit_notes/%Y/%m/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='saas_core.invoice')),
            ],
            options={
                'db_table': 'lumo_finance_credit_note',
            },
        ),
    ]
