# Generated by Django 6.0.6 on 2026-06-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0009_alter_invoice_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='allow_company_before_subscription',
            field=models.BooleanField(default=True, help_text='Allow creating 1 company before paying.'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='dashboard_requires_active_subscription',
            field=models.BooleanField(default=True, help_text='Lock dashboard if no active plan.'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='grace_period_days',
            field=models.IntegerField(default=7, help_text='Days before suspension after payment fails.'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='max_payment_retries',
            field=models.IntegerField(default=3, help_text='Dunning engine retry limit.'),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='trial_enabled',
            field=models.BooleanField(default=False, help_text='Global switch to enable/disable trials.'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='allow_signup',
            field=models.BooleanField(default=True, help_text='Allow direct checkout'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_free_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_popular',
            field=models.BooleanField(default=False, help_text='Highlight as Most Popular'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Show on public pricing page'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='is_trial_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='requires_sales_contact',
            field=models.BooleanField(default=False, help_text='Hide price, show Contact Sales'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='suspension_reason',
            field=models.CharField(blank=True, choices=[('PAYMENT_FAILURE', 'Payment Failure'), ('ABUSE', 'Policy Abuse / Terms Violation'), ('ADMIN', 'Admin Action')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfiguration',
            name='support_email',
            field=models.EmailField(default='support@lumodigital.co', max_length=254),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='api_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Auto-assign on onboarding'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='workspacesubscription',
            name='status',
            field=models.CharField(choices=[('TRIALING', 'Trialing'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('CANCELED', 'Canceled'), ('EXPIRED', 'Expired'), ('PENDING_PAYMENT', 'Pending Payment')], default='TRIALING', max_length=20),
        ),
    ]
