# Generated by Django 6.0.6 on 2026-06-23 20:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0010_globalconfiguration_allow_company_before_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
