# Generated by Django 6.0.6 on 2026-06-23 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0011_billingprofile_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingprofile',
            name='tax_registration_type',
            field=models.CharField(blank=True, choices=[('VAT', 'VAT Number'), ('GST', 'GST Number'), ('EIN', 'Employer Identification Number (US)'), ('ABN', 'Australian Business Number'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
