# Generated by Django 6.0.6 on 2026-06-24 05:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0012_alter_billingprofile_tax_registration_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditnote',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='public_token',
            field=models.CharField(db_index=True, default=uuid.uuid4, editable=False, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='processedwebhookevent',
            name='event_id',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='processedwebhookevent',
            name='event_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='processedwebhookevent',
            name='gateway_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='processedwebhookevent',
            name='status',
            field=models.CharField(default='PROCESSED', max_length=20),
        ),
    ]
