# Generated by Django 6.0.6 on 2026-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas_core', '0013_alter_creditnote_reason_alter_invoice_public_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalconfiguration',
            name='api_domain',
            field=models.CharField(default='api.lumodigital.co', max_length=255),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='app_domain',
            field=models.CharField(default='app.lumodigital.co', help_text='e.g., app.lumodigital.co', max_length=255),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='base_domain',
            field=models.CharField(default='lumodigital.co', help_text='e.g., lumodigital.co', max_length=255),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='cdn_domain',
            field=models.CharField(default='cdn.lumodigital.co', max_length=255),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='media_domain',
            field=models.CharField(default='media.lumodigital.co', max_length=255),
        ),
        migrations.AddField(
            model_name='globalconfiguration',
            name='portal_prefix',
            field=models.CharField(default='portal', help_text="e.g., 'portal' -> portal.sauda.com", max_length=50),
        ),
    ]
