# Generated by Django 6.0.6 on 2026-06-24 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atomicsectionversion',
            name='capabilities',
            field=models.JSONField(default=list, help_text='e.g., ["supports_background_image", "supports_dark_mode"]'),
        ),
        migrations.AddField(
            model_name='atomicsectionversion',
            name='is_i18n_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mediaasset',
            name='checksum',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
