# Generated by Django 6.0.6 on 2026-06-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0002_atomicsectionversion_capabilities_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitekitmanifest',
            options={'ordering': ['page_slug', 'default_sort_order']},
        ),
        migrations.AddField(
            model_name='sitekitmanifest',
            name='is_required',
            field=models.BooleanField(default=True, help_text='If false, this section is available but hidden by default.'),
        ),
        migrations.AddField(
            model_name='sitekitmanifest',
            name='page_slug',
            field=models.CharField(default='home', help_text="e.g., 'home', 'about-us', 'contact'", max_length=100),
        ),
        migrations.AddField(
            model_name='sitekitmanifest',
            name='starter_content_json',
            field=models.JSONField(blank=True, default=dict, help_text='The initial data injected when the kit is provisioned.'),
        ),
    ]
