# Generated by Django 6.0.6 on 2026-06-25 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0003_alter_sitekitmanifest_options_and_more'),
        ('saas_core', '0013_alter_creditnote_reason_alter_invoice_public_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdefinition',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_definitions', to='saas_core.workspace'),
        ),
        migrations.AddField(
            model_name='formsubmission',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_submissions', to='saas_core.workspace'),
        ),
        migrations.AddField(
            model_name='pagerevision',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_revisions', to='saas_core.workspace'),
        ),
        migrations.AddField(
            model_name='sitedeployment',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='saas_core.workspace'),
        ),
        migrations.AddField(
            model_name='sitemenu',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_menus', to='saas_core.workspace'),
        ),
        migrations.AddField(
            model_name='sitemenuitem',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='saas_core.workspace'),
        ),
        migrations.AddField(
            model_name='tenantpage',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tenant_pages', to='saas_core.workspace'),
        ),
        migrations.AddField(
            model_name='tenantpagesection',
            name='lock_version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='tenantpagesection',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_sections', to='saas_core.workspace'),
        ),
        migrations.AlterField(
            model_name='sitekitmanifest',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='sitekitmanifest',
            name='starter_content_json',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
