# Generated by Django 6.0.6 on 2026-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0004_formdefinition_workspace_formsubmission_workspace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domainverification',
            name='cloudflare_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='domainverification',
            name='ownership_txt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domainverification',
            name='ownership_txt_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domainverification',
            name='ssl_txt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domainverification',
            name='ssl_txt_value',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domainverification',
            name='dns_target',
            field=models.CharField(default='cname.lumo-os.com', max_length=255),
        ),
        migrations.AlterField(
            model_name='domainverification',
            name='verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
