# Generated by Django 6.0.6 on 2026-06-25 11:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0005_domainverification_cloudflare_id_and_more'),
        ('saas_core', '0013_alter_creditnote_reason_alter_invoice_public_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePublishedSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by_id', models.UUIDField(blank=True, null=True)),
                ('updated_by_id', models.UUIDField(blank=True, null=True)),
                ('deleted_by_id', models.UUIDField(blank=True, null=True)),
                ('rendered_html', models.TextField(blank=True, null=True)),
                ('page_data_snapshot', models.JSONField(default=dict)),
                ('version', models.PositiveIntegerField(default=1)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='published_snapshot', to='lumo_sites.tenantpage')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saas_core.workspace')),
            ],
            options={
                'db_table': 'lumo_sites_page_snapshot',
            },
        ),
    ]
