# Generated by Django 6.0.6 on 2026-06-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0006_pagepublishedsnapshot'),
        ('saas_core', '0013_alter_creditnote_reason_alter_invoice_public_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitekitmanifest',
            name='page_slug',
            field=models.CharField(default='home', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='tenantpagesection',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('revision', 'sort_order'), name='unique_sort_order_per_revision'),
        ),
    ]
