# Generated by Django 6.0.6 on 2026-06-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0007_alter_sitekitmanifest_page_slug_and_more'),
        ('saas_core', '0013_alter_creditnote_reason_alter_invoice_public_token_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pagerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'DRAFT')), fields=('page',), name='unique_draft_per_page'),
        ),
        migrations.AddConstraint(
            model_name='pagerevision',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), ('status', 'PUBLISHED')), fields=('page',), name='unique_published_per_page'),
        ),
    ]
