# Generated by Django 6.0.6 on 2026-06-28 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0008_pagerevision_unique_draft_per_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsite',
            name='body_scripts',
            field=models.TextField(blank=True, help_text='Injected before </body>', null=True),
        ),
        migrations.AddField(
            model_name='tenantsite',
            name='default_social_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_social_images', to='lumo_sites.mediaasset'),
        ),
        migrations.AddField(
            model_name='tenantsite',
            name='favicon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_favicons', to='lumo_sites.mediaasset'),
        ),
        migrations.AddField(
            model_name='tenantsite',
            name='head_scripts',
            field=models.TextField(blank=True, help_text='Injected before </head>', null=True),
        ),
        migrations.AddField(
            model_name='tenantsite',
            name='logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_logos', to='lumo_sites.mediaasset'),
        ),
    ]
