# Generated by Django 6.0.6 on 2026-06-28 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0009_tenantsite_body_scripts_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemenuitem',
            name='linked_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_references', to='lumo_sites.tenantpage'),
        ),
        migrations.AlterField(
            model_name='sitemenuitem',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
