# Generated by Django 6.0.6 on 2026-06-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumo_sites', '0010_sitemenuitem_linked_page_alter_sitemenuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitedomain',
            name='dns_status',
            field=models.CharField(choices=[('PENDING', 'Pending Configuration'), ('VERIFYING', 'Verifying Records'), ('ACTIVE', 'Active & Propagated'), ('FAILED', 'Verification Failed'), ('INVALID', 'Invalid Configuration')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='sitedomain',
            name='domain_type',
            field=models.CharField(choices=[('PLATFORM', 'System Platform Domain'), ('APP', 'SaaS App/Builder Domain'), ('TENANT_SITE', 'Tenant Public Website'), ('PORTAL', 'Customer/Vendor Portal'), ('API', 'API Endpoint'), ('MEDIA', 'Media Storage'), ('CDN', 'Content Delivery Network'), ('CUSTOM', 'Custom Routing')], default='TENANT_SITE', max_length=20),
        ),
    ]
